steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/m2c-demo/container/code-oss-customize', '.']
images: ['us-central1-docker.pkg.dev/m2c-demo/container/code-oss-customize']
